#!/usr/bin/env bash

COMMON_FOLDER=$(printf "%q\n" "$(pwd)")
echo "Commondir: $COMMON_FOLDER"

HYBRIS_HOME=$COMMON_FOLDER/hybris
echo "Hybris homedir: $HYBRIS_HOME"

HYBRIS_BIN_DIR=$HYBRIS_HOME/bin
echo "Hybris bindir: $HYBRIS_BIN_DIR"

HYBRIS_DATA_DIR=$HYBRIS_HOME/data

HYBRIS_TEMP_DIR=$HYBRIS_HOME/temp

HYBRIS_LOG_DIR=$HYBRIS_HOME/log

export COMMON_FOLDER HYBRIS_HOME HYBRIS_BIN_DIR HYBRIS_DATA_DIR HYBRIS_TEMP_DIR HYBRIS_LOG_DIR
